sonar.projectKey=alleni-samar_projet_laravel
sonar.organization=alleni-samar
sonar.projectName=PFA Laravel Chatbot
sonar.sources=app,routes,database
sonar.tests=tests
sonar.php.coverage.reportPaths=reports/coverage.xml
sonar.exclusions=vendor/**,node_modules/**,public/**