name: SonarCloud Analysis

on:
  push:
    branches: [ "main", "master" , "backends" , "frontends"]
  pull_request:
    branches: [ "main", "master" ]

    
jobs:
  sonar:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: pcov

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Prepare Environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run PHPUnit + Coverage
        run: |
          mkdir -p reports
          ./vendor/bin/phpunit --coverage-clover=reports/coverage.xml --log-junit=reports/junit.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
